env:
  - version=1.2.4
  - version=1.2.3
  - version=1.2.2
  - version=1.2.0
  - version=1.1.7
  - version=1.2.6
  - version=1.1.5
  - version=1.1.4
  - version=1.1.3
  - version=1.1.2
  
  
os: linux-ppc64le
dist: xenial
sudo: required
# setup travis so that we can run containers for integration tests
services:
  - docker

language: go

go:
  - "1.11.x"

go_import_path: github.com/containerd/
go_import_path: github.com/opencontainers/

addons:
  apt:
    packages:
      - btrfs-tools
      - libnl-3-dev
      - libnet-dev
      - protobuf-c-compiler
      # - protobuf-compiler
      - python-minimal
      - libcap-dev
      - libaio-dev
      - libprotobuf-c0-dev
      - libprotobuf-dev
      - socat
      - libseccomp-dev
  
  
before_install:
  - sudo apt install -y lftp
  - wget -c https://github.com/protocolbuffers/protobuf/releases/download/v3.7.1/protoc-3.7.1-linux-ppcle_64.zip
  - sudo unzip protoc-3.7.1-linux-ppcle_64.zip -d /usr/local
  - sudo apt-get install -y btrfs-tools
  - cd $GOPATH/src/github.com/opencontainers  
  - git clone https://github.com/opencontainers/runc.git
  - cd runc
  - make
  - sudo make install


script:
  - cd $GOPATH/src/github.com
  - mkdir containerd
  - cd containerd
  - wget https://github.com/containerd/containerd/archive/v$version.zip
  - unzip v$version.zip
  - mv containerd-$version containerd
  - cd containerd
  - make VERSION=version
  - cd bin
  - lftp -c "open -u $USER,$PASS ftp://oplab9.parqtec.unicamp.br; cd /ppc64el/containerd; mkdir containerd-$version"
  - lftp -c "open -u $USER,$PASS ftp://oplab9.parqtec.unicamp.br; put -O /ppc64el/containerd/containerd-$version ctr"
  - lftp -c "open -u $USER,$PASS ftp://oplab9.parqtec.unicamp.br; put -O /ppc64el/containerd/containerd-$version containerd"
  - lftp -c "open -u $USER,$PASS ftp://oplab9.parqtec.unicamp.br; put -O /ppc64el/containerd/containerd-$version containerd-stress"
  - lftp -c "open -u $USER,$PASS ftp://oplab9.parqtec.unicamp.br; put -O /ppc64el/containerd/containerd-$version containerd-shim"
  - lftp -c "open -u $USER,$PASS ftp://oplab9.parqtec.unicamp.br; put -O /ppc64el/containerd/containerd-$version containerd-shim-runc-v1"
  - lftp -c "open -u $USER,$PASS ftp://oplab9.parqtec.unicamp.br; put -O /ppc64el/containerd/containerd-$version containerd-shim-runc-v2"

  
