#funciona!
os: linux
arch: ppc64le
dist: bionic
sudo: required
# setup travis so that we can run containers for integration tests
services:
  - docker

language: go

go:
  - "1.14.x"

install:
  - sudo apt update
  - sudo apt install btrfs-tools libnl-3-dev libnet-dev protobuf-c-compiler python-minimal libcap-dev libaio-dev libprotobuf-c0-dev libprotobuf-dev socat libseccomp-dev
  #- export GOPATH=~/gopath
  #- mkdir src bin pkg
  #- sudo apt update
  - sudo apt install lftp python3 rpm
  #- sudo apt install gcc make pkg-config unzip
  - go get github.com/opencontainers/runc
  - cd $GOPATH/src/github.com/opencontainers/runc
  #- git clone https://github.com/opencontainers/runc.git
  #- cd runc
  - make
  - sudo make install

script:
  - cd $TRAVIS_BUILD_DIR
  - python3 ftp_version.py
  - python3 validation.py
  - bash build.sh
  - bash release.sh

notifications:
  slack:
    rooms:
      - secure: "p+7jsGyXFMkq1SxKV+3zJWkpHcBWKmxaiKfW7yoBN7H8T+XSLyzttOnqbGg97cRvnfUW5dg485h8hxcvVfu4d2H9A5cfJKyIs7GqdFPi9MzrZFvQXTz7qs58r/MO1l5ks0W0OKvzv+vEmU2B6e+eMwq27RNnNC8QoMYBVEPI+E46PI3sJhh4dC4LcxqlN1SkDGrFu6Buv5TioefDsJ78DeXVVhgeI8X7jP8uG/A46mq4O857xMwEkwJdlofbhC8CYdtqjjOMrpuTorDI8HInxaWJlHasZ6TJl9hEeIeUp4Cq/KkO3s7uE1tA14OFMoNsVzFH+nN+zV5Rt2w02ehFaP66C3HxgsEgHXO/s/l0aZt1Hjmcczu86hJziZCKgtMj7OEdt+hRaNsvJy8epyG9rS3+xcXFk8Z/kJXcM/ZdNeIlViaqTyJdGf5HTcw3ZI7q5ywYHyaPLwxidqsSVq+qiLGb8D4s/Kvs2HRMGXKjnd30I+l887rxcc5GGSPpDQmYGszuTDMMQ5O3LH3eSAykQeZJbIQ0wKKA+33fSvGsCVLd46cXdls7+fA2+muiFMZG9tN9ICRvpJVZDNpPe0gFtzsFJNQtTQeGeoS7tQsdi/YCoJmcRVpjIp+sAipZJo7DSHdep5IvgYCqTL4GXqD6FeHZJBpszx9B+rdTiwOcbkg="
    on_success: change
    on_failure: change
