os: linux-ppc64le
dist: xenial
sudo: required
# setup travis so that we can run containers for integration tests
services:
  - docker

language: go

go:
  - "1.11.x"

go_import_path: github.com/containerd/
go_import_path: github.com/opencontainers/

addons:
  apt:
    packages:
      - btrfs-tools
      - libnl-3-dev
      - libnet-dev
      - protobuf-c-compiler
      # - protobuf-compiler
      - python-minimal
      - libcap-dev
      - libaio-dev
      - libprotobuf-c0-dev
      - libprotobuf-dev
      - socat
      - libseccomp-dev
  
  
before_install:
  - python3 ftp_version.py

script:
  - bash build.sh
