matrix:
  include:
    - env: ver=1.2.1
    - env: ver=1.1.5
    - env: ver=1.2.0
    - env: ver=1.1.4
    - env: ver=1.1.3
    
os: linux-ppc64le
dist: xenial
sudo: required
# setup travis so that we can run containers for integration tests
services:
  - docker

language: go

go:
  - "1.11.x"

go_import_path: github.com/containerd/
go_import_path: github.com/opencontainers/

addons:
  apt:
    packages:
      - btrfs-tools
      - libnl-3-dev
      - libnet-dev
      - protobuf-c-compiler
      # - protobuf-compiler
      - python-minimal
      - libcap-dev
      - libaio-dev
      - libprotobuf-c0-dev
      - libprotobuf-dev
      - socat
      - libseccomp-dev
  
  
before_install:
  - sudo apt install -y lftp
  - wget -c https://github.com/protocolbuffers/protobuf/releases/download/v3.7.1/protoc-3.7.1-linux-ppcle_64.zip
  - sudo unzip protoc-3.7.1-linux-ppcle_64.zip -d /usr/local
#  - sudo apt install -y btrfs-tools
  
 # - cd $GOPATH/src/github.com/opencontainers
 # - git clone https://github.com/opencontainers/runc.git
 # - cd runc
 # - make
 # - sudo make install
 
  - go get github.com/opencontainers/runc
  - cd $GOPATH/src/github.com/opencontainers/runc
  - make
  - sudo make install

script:  
  - cd /home/travis/gopath/src/github.com/opencontainers
  - python3 ftp_version.py
  - bash build.sh
